In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [6]:
a = np.array( [1,2] )
print(a)
print(dir(a))

[1 2]
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rl

In [11]:
a = np.array( (1,2) )
print(a)
print(type(a))
print(a.ndim)
print(a.size)
print(a.shape)

[1 2]
<class 'numpy.ndarray'>
1
2
(2,)


In [15]:
a = np.array( [(1,2,3), (2,3,4)] )
print(a)
print(type(a))
print(a.ndim)
print(a.size)
print(a.shape)
print(a.itemsize)
print(a.dtype)

[(1, 2, 3) (2, 3)]
<class 'numpy.ndarray'>
1
2
(2,)
8
object


In [17]:
a = np.array( (1,2.0) )
print(a.dtype)

float64


In [18]:
a = np.array( (1,2.0), dtype = 'float32' )
print(a.dtype)

float32


In [27]:
a = np.array( (1,2.0), dtype = 'int32' )
print(a.dtype, a)
a = np.array( (1,2,3,4), dtype = 'int8' )
print(a.dtype, a)
a = np.array( (1,2,3,4000), dtype = np.uint32 )
print(a.dtype, a)
a = np.array( (1,2,3,400000000) )
print(a.dtype, a)

int32 [1 2]
int8 [1 2 3 4]
uint32 [   1    2    3 4000]
int32 [        1         2         3 400000000]


In [30]:
a = np.array( ['abcdb', 'ab'])
print(a.dtype)
print(a.itemsize)
print(a.size)

<U5
20
2


In [31]:
a = np.array( [10,20], dtype = 'b')
print(a.dtype)
print(a.itemsize)
print(a.size)

int8
1
2


In [35]:
print(np.arange(10))
print(np.arange(10,20))
print(np.arange(10,20,2))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [36]:
r = np.arange(10)
print(r)
r = range(10)
print(r)

[0 1 2 3 4 5 6 7 8 9]
range(0, 10)


In [47]:
print(np.random.randint(10,20,5))
print(np.random.randint(10))
print(np.random.randint(10,20))

print(help(np.random.randint))
print(dir(np.random))

[11 16 11 10 11]
9
17
Help on built-in function randint:

randint(...) method of mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    Parameters
    ----------
    low : int
        Lowest (signed) integer to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above for behavior if ``high=None``).
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are draw

In [57]:
print(np.random.random()) # normal distribution; gaussian

0.5949357416193104


In [67]:
ar = np.array(range(1,11)) 
print(ar)
np.random.shuffle(ar)
print(ar)

[ 1  2  3  4  5  6  7  8  9 10]
[ 8  1  5  3  6  7  4 10  2  9]


In [71]:
a = np.linspace(10,20, 6) # linear space
print(a)
a = np.linspace(10,20, 100) # linear space
print(a)

[10. 12. 14. 16. 18. 20.]
[10.         10.1010101  10.2020202  10.3030303  10.4040404  10.50505051
 10.60606061 10.70707071 10.80808081 10.90909091 11.01010101 11.11111111
 11.21212121 11.31313131 11.41414141 11.51515152 11.61616162 11.71717172
 11.81818182 11.91919192 12.02020202 12.12121212 12.22222222 12.32323232
 12.42424242 12.52525253 12.62626263 12.72727273 12.82828283 12.92929293
 13.03030303 13.13131313 13.23232323 13.33333333 13.43434343 13.53535354
 13.63636364 13.73737374 13.83838384 13.93939394 14.04040404 14.14141414
 14.24242424 14.34343434 14.44444444 14.54545455 14.64646465 14.74747475
 14.84848485 14.94949495 15.05050505 15.15151515 15.25252525 15.35353535
 15.45454545 15.55555556 15.65656566 15.75757576 15.85858586 15.95959596
 16.06060606 16.16161616 16.26262626 16.36363636 16.46464646 16.56565657
 16.66666667 16.76767677 16.86868687 16.96969697 17.07070707 17.17171717
 17.27272727 17.37373737 17.47474747 17.57575758 17.67676768 17.77777778
 17.87878788 17.97979798 

In [75]:
print(np.ones(10, dtype = np.int8))
print(np.ones( (10,3)) )

[1 1 1 1 1 1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [76]:
print(np.ones( (2,3,4)) )

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [79]:
print(np.zeros( (2,4,3,4)) )

[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [5]:
a = np.arange(1,21)
r = a.reshape(4,5)
print(a)
print(r)
r1 = a.reshape(4,4)
print(r1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


ValueError: cannot reshape array of size 20 into shape (4,4)

In [9]:
a = np.arange(1,21)
a.resize(4,5)
print(a)
a.resize(4,4)
print(a)
a.resize(4,6)
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16  0  0]
 [ 0  0  0  0  0  0]]


In [20]:
a = np.arange(100,121)
a.resize(4,5)
print(a)

print()
print( a[0]) # row
print()
print( a[0:2] )

print('Columns')
print( a[:,2])
print()
print( a[:,2:])

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]

[100 101 102 103 104]

[[100 101 102 103 104]
 [105 106 107 108 109]]
Columns
[102 107 112 117]

[[102 103 104]
 [107 108 109]
 [112 113 114]
 [117 118 119]]


In [25]:
a = np.arange(100,121)
a.resize(4,5)
print(a)
print()
print( a[1:3,2:])

print()
print( a[ [0,3] ])

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]

[[107 108 109]
 [112 113 114]]

[[100 101 102 103 104]
 [115 116 117 118 119]]



IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [34]:
a = np.arange(100,121)
a.resize(4,5)
print(a)
print()
print( a[ [1,2,3]  ])
print()
print( a[ (1,2,3), (1,3,4) ])
print()
print( a[ np.array([1,2])  ])
print()
print( a[ range(1,3) ])
print()
print(a[  0,3   ])

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]

[[105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]



IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [54]:
print(a)
print(  a[ [0,2]  ] [:,[2,3,4]] )
print(a[0,3]    , [1,10])
print(a[:,::2])
print(a[::-1])

[[100 101 102 103 104]
 [105 106 107 108 109]
 [110 111 112 113 114]
 [115 116 117 118 119]]
[[102 103 104]
 [112 113 114]]
103 [1, 10]
[[100 102 104]
 [105 107 109]
 [110 112 114]
 [115 117 119]]
[[115 116 117 118 119]
 [110 111 112 113 114]
 [105 106 107 108 109]
 [100 101 102 103 104]]


In [ ]:
() -> function call except tuples
[] -> creating python list ; to index or slice array kind of data


In [33]:
t = (10,20,30,40)
print(t[1]) # index
print(t[1:3]) # slice 


20
(20, 30)


In [56]:
a = np.random.randint(10,20,10)
print(a)

[10 15 11 16 18 12 17 16 15 16]


In [59]:
print(a)
print(a > 15)
print(a[ a > 15 ])

[10 15 11 16 18 12 17 16 15 16]
[False False False  True  True False  True  True False  True]
[16 18 17 16 16]


In [60]:
print(a)
print(a*10) # broadcasting

[10 15 11 16 18 12 17 16 15 16]
[100 150 110 160 180 120 170 160 150 160]


In [63]:
b = np.random.randint(1000,2000,9)
print(b)

[1002 1376 1922 1855 1357 1606 1546 1164 1437]


In [64]:
print(a*b)

ValueError: operands could not be broadcast together with shapes (10,) (9,) 

In [69]:
print(np.identity( 3 ))

print(np.arange(1,11))
print(np.arange(1,11).reshape(10,1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [72]:
a.resize(4,5)
print(a)
print(a[0] * a[1])

[[10 15 11 16 18]
 [12 17 16 15 16]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[120 255 176 240 288]


In [76]:
print( np.arange(10,20) )
print( np.arange(40,51) )

[10 11 12 13 14 15 16 17 18 19]
[40 41 42 43 44 45 46 47 48 49 50]


In [98]:
a = np.random.randint(10,90, 20)
a.resize(4,5)
print(a)

[[88 53 72 44 34]
 [72 49 31 89 60]
 [79 89 11 13 50]
 [59 74 47 64 75]]


In [84]:
print(a.max())
print(a.mean())
print(a.sum())

83
49.7
994

[80 83 81 69]
49.7
994


In [86]:
print(a)
print(a.max(axis=1))
print(a.mean(axis=1))
print(a.sum(axis=1))

[[32 31 80 61 70]
 [75 70 30 83 20]
 [41 81 26 24 68]
 [29 55 69 13 36]]
[80 83 81 69]
[54.8 55.6 48.  40.4]
[274 278 240 202]


In [87]:
print(a)
print(a.max(axis=0))
print(a.mean(axis=0))
print(a.sum(axis=0))

[[32 31 80 61 70]
 [75 70 30 83 20]
 [41 81 26 24 68]
 [29 55 69 13 36]]
[75 81 80 83 70]
[44.25 59.25 51.25 45.25 48.5 ]
[177 237 205 181 194]


In [93]:
ab = np.array( [1,2,np.nan, 10, np.nan])
print(ab)
r = np.isnan(ab)
print(r)
r.sum()

[ 1.  2. nan 10. nan]
[False False  True False  True]


2

In [94]:
a

array([[32, 31, 80, 61, 70],
       [75, 70, 30, 83, 20],
       [41, 81, 26, 24, 68],
       [29, 55, 69, 13, 36]])

In [102]:
r = a%2 == 0
print(r)
r_dash = ~r 
print(r_dash)
print(r.sum())
print(r_dash.sum())
print(len(a))
print(a.size, a.shape)

[[ True False  True  True  True]
 [ True False False False  True]
 [False False False False  True]
 [False  True False  True False]]
[[False  True False False False]
 [False  True  True  True False]
 [ True  True  True  True False]
 [ True False  True False  True]]
9
11
4
20 (4, 5)


In [108]:
print(a)
print(a>50)
print(a<70)
r = (a>50) & (a < 70)
print(r ) # &-> and | -> or
print(a[ r ])


[[88 53 72 44 34]
 [72 49 31 89 60]
 [79 89 11 13 50]
 [59 74 47 64 75]]
[[ True  True  True False False]
 [ True False False  True  True]
 [ True  True False False False]
 [ True  True False  True  True]]
[[False  True False  True  True]
 [False  True  True False  True]
 [False False  True  True  True]
 [ True False  True  True False]]
[[False  True False False False]
 [False False False False  True]
 [False False False False False]
 [ True False False  True False]]
[53 60 59 64]
