In [2]:
import pandas as pd # Panel Data
import numpy as np

In [3]:
print(dir(pd))

['Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Float64Index', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int64Index', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NaT', 'Panel', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseArray', 'SparseDataFrame', 'SparseDtype', 'SparseSeries', 'TimeGrouper', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt64Index', 'UInt8Dtype', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_hashtable', '_lib', '_libs', '_np_version_under1p13', '_np_version_under1p14', '_np_version_under1p15', '_np_version_under1p16', '_np_version_under1p17', '_tslib', '_version', 'api', 'array', 'arrays', 'bdate_rang

In [19]:
s = pd.Series(dtype = 'int8')
print(s)
print()
s = pd.Series([10,20,30,40])
print(s)

s = pd.Series(np.arange(10,50,10))
print(s)
print(s.index)
print(s.values)

Series([], dtype: int8)

0    10
1    20
2    30
3    40
dtype: int64
0    10
1    20
2    30
3    40
dtype: int32
RangeIndex(start=0, stop=4, step=1)
[10 20 30 40]


In [9]:
s = pd.Series()
print(dir(s))

['T', '_AXIS_ALIASES', '_AXIS_IALIASES', '_AXIS_LEN', '_AXIS_NAMES', '_AXIS_NUMBERS', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_SLICEMAP', '__abs__', '__add__', '__and__', '__array__', '__array_prepare__', '__array_priority__', '__array_wrap__', '__bool__', '__bytes__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod_

In [12]:
ar = np.random.randint(1,50,40).reshape(10,4)
print(ar)

[[ 2 40 36 38]
 [ 9  1 23  7]
 [25 23  1 39]
 [36 37  3  7]
 [41  5 43 49]
 [ 3 11 23 25]
 [33  4 43  4]
 [48 23 25  7]
 [ 5 24  3 42]
 [ 9 44 41 17]]


In [23]:
df = pd.DataFrame(ar)
print(df)

print(df.shape)
print(df.size)
print(df.columns)
print(df.index)
print(df.dtypes)

print(df.columns.dtype)

# DataFrame from Dictionary

    0   1   2   3
0   2  40  36  38
1   9   1  23   7
2  25  23   1  39
3  36  37   3   7
4  41   5  43  49
5   3  11  23  25
6  33   4  43   4
7  48  23  25   7
8   5  24   3  42
9   9  44  41  17
(10, 4)
40
RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=10, step=1)
0    int32
1    int32
2    int32
3    int32
dtype: object
int64


In [33]:
df = pd.DataFrame(ar, index = list('abcdefghij'), columns = ['AB','C','D','E'])
print(df)
print(df.columns)
print(df.index)
print(df.columns.values)
print('\n')
print(df.dtypes)
print('Columns')
print(df.columns.dtype)


   AB   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49
f   3  11  23  25
g  33   4  43   4
h  48  23  25   7
i   5  24   3  42
j   9  44  41  17
Index(['AB', 'C', 'D', 'E'], dtype='object')
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')
['AB' 'C' 'D' 'E']


AB    int32
C     int32
D     int32
E     int32
dtype: object
Columns
object


In [26]:
print(df)

   AB   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49
f   3  11  23  25
g  33   4  43   4
h  48  23  25   7
i   5  24   3  42
j   9  44  41  17


In [28]:
print(df.head()) # 5
print(df.tail()) # 5

   AB   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49
   AB   C   D   E
f   3  11  23  25
g  33   4  43   4
h  48  23  25   7
i   5  24   3  42
j   9  44  41  17


In [35]:
df = pd.DataFrame(ar, index = list('abcdefghij'), columns = ['AB','C','D','E'])
print(df.head(2)) 
print(df.tail(2))
#df.loc['a','b'] = np.nan
print(df.describe())

   AB   C   D   E
a   2  40  36  38
b   9   1  23   7
   AB   C   D   E
i   5  24   3  42
j   9  44  41  17
              AB          C          D         E
count  10.000000  10.000000  10.000000  10.00000
mean   21.100000  21.200000  24.100000  23.50000
std    17.457568  15.661701  16.894772  17.27072
min     2.000000   1.000000   1.000000   4.00000
25%     6.000000   6.500000   8.000000   7.00000
50%    17.000000  23.000000  24.000000  21.00000
75%    35.250000  33.750000  39.750000  38.75000
max    48.000000  44.000000  43.000000  49.00000


In [40]:
print(df.head())
d = {'AB': 'A'}
df1 = df.rename(columns = d)
print(df1.head())
print(df.head())

   AB   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49
    A   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49
   AB   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49


In [42]:
print(df.head())
d = {'AB': 'A'}
df1 = df.rename(columns = d, inplace = True)
print(df1)
print(df.head())


    A   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49
None
    A   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49


In [44]:
print(df.head())
d = {'a': 'A'}
df.rename(d, inplace = True, axis = 0)
print(df.head())


    A   C   D   E
a   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49
    A   C   D   E
A   2  40  36  38
b   9   1  23   7
c  25  23   1  39
d  36  37   3   7
e  41   5  43  49


In [5]:
ar = np.random.randint(10,50,40).reshape(10,4)
df = pd.DataFrame(ar, index = list('abcdefghij'), columns = ['AB','C','D','E'])

In [6]:
print(df)

   AB   C   D   E
a  28  36  18  34
b  21  27  42  12
c  14  29  27  29
d  36  25  25  36
e  12  44  44  49
f  25  34  47  21
g  28  10  35  46
h  16  28  13  29
i  14  18  18  43
j  31  25  11  42


In [7]:
print(df['AB'])

a    28
b    21
c    14
d    36
e    12
f    25
g    28
h    16
i    14
j    31
Name: AB, dtype: int32


In [23]:
print(df['a':'c'])
print(df['a':'c'].sum(axis = 1))

   AB   C   D   E
a  28  36  18  34
b  21  27  42  12
c  14  29  27  29
a    116
b    102
c     99
dtype: int64


In [19]:
print(df.loc['a','AB'])
print(df.loc['c':])
print(df.loc['c':'i', ['C','D'] ])

28
   AB   C   D   E
c  14  29  27  29
d  36  25  25  36
e  12  44  44  49
f  25  34  47  21
g  28  10  35  46
h  16  28  13  29
i  14  18  18  43
j  31  25  11  42
    C   D
c  29  27
d  25  25
e  44  44
f  34  47
g  10  35
h  28  13
i  18  18


In [13]:

print(df.loc[:, ['C','D'] ])

    C   D
a  36  18
b  27  42
c  29  27
d  25  25
e  44  44
f  34  47
g  10  35
h  28  13
i  18  18
j  25  11


In [18]:
print(df.iloc[0])
print()
print(df.iloc[0:5])
print()
print(df.iloc[0:5, 3])

AB    28
C     36
D     18
E     34
Name: a, dtype: int32

   AB   C   D   E
a  28  36  18  34
b  21  27  42  12
c  14  29  27  29
d  36  25  25  36
e  12  44  44  49

a    34
b    12
c    29
d    36
e    49
Name: E, dtype: int32


In [24]:
print(df.AB)

a    28
b    21
c    14
d    36
e    12
f    25
g    28
h    16
i    14
j    31
Name: AB, dtype: int32
